# Generated by Django 4.1.1 on 2022-09-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cartoons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время обновления"
                    ),
                ),
                (
                    "datetime_deleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время удаления"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                (
                    "released",
                    models.CharField(max_length=255, verbose_name="дата выпуска"),
                ),
                ("img", models.ImageField(upload_to=None, verbose_name="афиша")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="описание"),
                ),
            ],
            options={
                "verbose_name": "Список Мультфильмов",
                "verbose_name_plural": "Списки Мультфильмов",
            },
        ),
        migrations.CreateModel(
            name="SerialRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время обновления"
                    ),
                ),
                (
                    "datetime_deleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время удаления"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="имя"),
                ),
                (
                    "bad_or_good",
                    models.CharField(
                        choices=[
                            ("Негативный персонаж", "Negative Character"),
                            ("Позитивный персонаж", "Positive Character"),
                            ("Нейтральный персонаж", "Neutral Character"),
                        ],
                        default="Нейтральный персонаж",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                ("main_person", models.BooleanField(default=False, verbose_name="имя")),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время создания"
                    ),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время обновления"
                    ),
                ),
                (
                    "datetime_deleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время удаления"
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="фамилия")),
                ("photo_url", models.ImageField(upload_to=None, verbose_name="фото")),
                (
                    "first_appearance_in_serial",
                    models.DateField(verbose_name="Первое появление в сериале"),
                ),
                ("date_birthday", models.DateField(verbose_name="Дата рождения")),
                (
                    "serial_role",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.serialrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
            },
        ),
    ]
