# Generated by Django 4.1.1 on 2022-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_anime_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="description",
            field=models.CharField(max_length=25, null=True, verbose_name="студия"),
        ),
        migrations.AlterField(
            model_name="anime",
            name="link",
            field=models.CharField(max_length=25, null=True, verbose_name="ссылка"),
        ),
        migrations.AlterField(
            model_name="anime",
            name="name",
            field=models.CharField(max_length=25, null=True, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="anime",
            name="rating",
            field=models.IntegerField(null=True, verbose_name="рейтинг"),
        ),
        migrations.AlterField(
            model_name="anime",
            name="studio",
            field=models.CharField(max_length=25, null=True, verbose_name="студия"),
        ),
    ]
